// Mocks generated by Mockito 5.4.5 from annotations
// in raygun_cli/test/symbols_command_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:raygun_cli/src/symbols/symbols_api.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SymbolsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockSymbolsApi extends _i1.Mock implements _i2.SymbolsApi {
  MockSymbolsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> uploadSymbols({
    required String? appId,
    required String? token,
    required String? path,
    required String? version,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadSymbols, [], {
              #appId: appId,
              #token: token,
              #path: path,
              #version: version,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> listSymbols({
    required String? appId,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listSymbols, [], {#appId: appId, #token: token}),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteSymbols({
    required String? appId,
    required String? token,
    required String? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSymbols, [], {
              #appId: appId,
              #token: token,
              #id: id,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
