// Mocks generated by Mockito 5.4.5 from annotations
// in raygun_cli/test/deployments/deployments_command_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:raygun_cli/src/deployments/deployments_api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [DeploymentsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeploymentsApi extends _i1.Mock implements _i3.DeploymentsApi {
  MockDeploymentsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeClient_0(this, Invocation.getter(#httpClient)),
      ) as _i2.Client);

  @override
  _i4.Future<bool> createDeployment({
    required String? token,
    required String? apiKey,
    required String? version,
    String? ownerName,
    String? emailAddress,
    String? comment,
    String? scmIdentifier,
    String? scmType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#createDeployment, [], {
          #token: token,
          #apiKey: apiKey,
          #version: version,
          #ownerName: ownerName,
          #emailAddress: emailAddress,
          #comment: comment,
          #scmIdentifier: scmIdentifier,
          #scmType: scmType,
        }),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
