name: CI

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get --enforce-lockfile

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get --enforce-lockfile

      - name: Build Linux binary
        run: dart compile exe bin/raygun_cli.dart -o raygun-cli

      - name: Generate artifact checksums
        run: sha256sum raygun-cli pubspec.lock > SHA256SUMS

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: |
            raygun-cli
            pubspec.lock
            SHA256SUMS

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get --enforce-lockfile

      - name: Build MacOS binary
        run: dart compile exe bin/raygun_cli.dart -o raygun-cli

      - name: Generate artifact checksums
        run: shasum -a 256 raygun-cli pubspec.lock > SHA256SUMS

      - name: Upload MacOS binary
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: |
            raygun-cli
            pubspec.lock
            SHA256SUMS

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get --enforce-lockfile

      - name: Build Windows binary
        run: dart compile exe bin/raygun_cli.dart -o raygun-cli.exe

      - name: Generate artifact checksums
        shell: pwsh
        run: |
          Get-FileHash raygun-cli.exe,pubspec.lock -Algorithm SHA256 | ForEach-Object { "$($_.Hash.ToLower())  $($_.Path | Split-Path -Leaf)" } | Set-Content SHA256SUMS

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: |
            raygun-cli.exe
            pubspec.lock
            SHA256SUMS
